# Generated by Django 4.0.4 on 2022-07-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_news', models.CharField(max_length=40)),
                ('rating_news', models.IntegerField()),
                ('body_news', models.BinaryField()),
            ],
        ),
    ]
